"""0000 baseline

Captures the CURRENT schema (jobs, extracted_data, output_files) as the
starting point for Alembic — the app's schema evolution was previously a
hand-rolled ALTER TABLE ADD COLUMN shim in database.py, which could only
ever add nullable columns and never enforced NOT NULL, renames, drops, or
indexes (P2-44, DECISIONS.md 2026-09-19). Autogenerated against a fresh
empty SQLite DB and hand-reviewed against db_models.py — matches exactly,
no manual edits needed.

Revision ID: 0000
Revises:
Create Date: 2026-09-19

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0000'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('source_files', sa.Text(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('processing_warnings', sa.Text(), nullable=True),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('course', sa.String(length=200), nullable=True),
    sa.Column('semester', sa.String(length=100), nullable=True),
    sa.Column('exam_name', sa.String(length=200), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_data',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('students_json', sa.Text(), nullable=False),
    sa.Column('subjects_json', sa.Text(), nullable=False),
    sa.Column('raw_text_sample', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('output_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('file_size_kb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('output_files')
    op.drop_table('extracted_data')
    op.drop_table('jobs')
    # ### end Alembic commands ###
