"""0002 exam model

The relational bridge extraction needs before the seating planner (and
later features) can exist: today's pipeline only ever writes JSON blobs
(extracted_data.students_json/subjects_json) — a roster query has nothing
real to run against without actual rows. Creates colleges, courses, exams,
subject_offerings, students, enrollments (all org_id NOT NULL from
creation — no historical data to backfill into them, see DECISIONS.md
2026-09-19) and adds jobs.exam_id/college_id (nullable — an existing job
predating the exam+college picker is not retroactively assigned one).

Autogenerated against a fresh DB with 0000+0001 applied, then hand-reviewed
and adjusted: the two new FK constraints on `jobs` (exam_id, college_id)
are explicitly named (fk_jobs_exam_id, fk_jobs_college_id) rather than left
anonymous — autogenerate's own downgrade output warned an anonymous
constraint name would make `drop_constraint(None, ...)` fail outright.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-19

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_colleges_org_id'), ['org_id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_org_id'), ['org_id'], unique=False)

    op.create_table('exams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('programme_label', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sticker_label', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exams_org_id'), ['org_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('roll_number', sa.String(length=30), nullable=False),
    sa.Column('roll_sort_key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('college_id', sa.String(length=36), nullable=True),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'roll_number', name='uq_student_org_roll')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_roll_sort_key'), ['roll_sort_key'], unique=False)

    op.create_table('subject_offerings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('exam_id', sa.String(length=36), nullable=False),
    sa.Column('exam_code', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('paper_no', sa.String(length=20), nullable=True),
    sa.Column('group_label', sa.String(length=50), nullable=True),
    sa.Column('scheme_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'exam_id', 'exam_code', name='uq_offering_org_exam_code')
    )
    with op.batch_alter_table('subject_offerings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_offerings_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_offerings_org_id'), ['org_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('offering_id', sa.String(length=36), nullable=False),
    sa.Column('source_job_id', sa.String(length=36), nullable=True),
    sa.Column('status_override', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['subject_offerings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'offering_id', name='uq_enrollment_student_offering')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_offering_id'), ['offering_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_org_id'), ['org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('college_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_jobs_exam_id', 'exams', ['exam_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_jobs_college_id', 'colleges', ['college_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_jobs_college_id', type_='foreignkey')
        batch_op.drop_constraint('fk_jobs_exam_id', type_='foreignkey')
        batch_op.drop_column('college_id')
        batch_op.drop_column('exam_id')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_student_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_org_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_offering_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('subject_offerings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_offerings_org_id'))
        batch_op.drop_index(batch_op.f('ix_subject_offerings_exam_id'))

    op.drop_table('subject_offerings')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_roll_sort_key'))
        batch_op.drop_index(batch_op.f('ix_students_org_id'))

    op.drop_table('students')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_org_id'))

    op.drop_table('exams')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_org_id'))

    op.drop_table('courses')
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_colleges_org_id'))

    op.drop_table('colleges')
    # ### end Alembic commands ###
